movie/movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import movieapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie/movieapp/urls.py
from django.urls import path, include
from movieapp import views
app_name='movieapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('film/<int:movieid>/',views.details,name='details'),
    path('add/',views.add,name='add'),
    path('updated/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie/movieapp/models.py
from django.db import models

# Create your models here.
class film(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

movie/movieapp/forms.py
from django import forms
from .models import film

class updated(forms.ModelForm):
    class Meta:
        model=film
        fields=['name','desc','year','img']

movie/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import updated
from .models import film


# Create your views here.
def home(request):
    movie=film.objects.all()
    context={
        'films':movie
    }
    return render(request,'index.html',context)
def details(request,movieid):
    films=film.objects.get(id=movieid)
    return render(request,'details.html',{'id':films})

def add(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year', )
        img=request.FILES['img']
        films=film(name=name,desc=desc,year=year,img=img)
        films.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=film.objects.get(id=id)
    form=updated(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=film.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token  %}
<input type="text" name="name" placeholder="Enter movie name"><br>
<input type="text" name="desc" placeholder="Enter movie description"><br>
<input type="number" name="year" placeholder="Enter released year"><br>
<input type="file" name="img"><br>
<input type="submit">
</form>
{% endblock %}

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>movies</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    movies
  </a>
    <a class="btn btn-primary" href="{% url 'movieapp:add' %}">add</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit" value="yes">
</form>

{% endblock %}

movie/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{id.img.url}}" width="300" height="450">
        </div>
        <div class="col-md-8">
            <h3>{{id.name}}</h3>
            <h6>{{id.desc}}</h6>
            <h6>{{id.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' id.id%}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' id.id%}">delete</a>
        </div>
    </div>
</div>
{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}<br>
    <input type="submit">
</form>

{% endblock %}

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in films %}
            <div class="col-md-6">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="400">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
<!--<img src="{{i.img.url}}" width="100" height="150">-->
<!--<a href="{% url 'movieapp:details' i.id %}">  {{i.name}}</a><br>-->